### ISSUE TITLE
Adapt all "translation pages" to the new layout

### ISSUE THREAD

**Issue by onebree** [betterspecs/betterspecs#166]
Originated from https://github.com/lelylan/betterspecs/issues/153#issuecomment-182478368
- [ ] Adapt all "translation pages" to the new layout (priority)
- [ ] Place all translation pages in a more structured way, while maintaining today's paths

@benoittgt -- please coordinate with @akz92, as he will be working directly with the translations themselves.

**Comment by akz92** [comment]
Closing this issue as it's addressed in the recently opened issue about Betterspecs 2.0
