### ISSUE TITLE
Move translated texts to corresponding YAML file

### ISSUE THREAD

**Issue by akz92** [betterspecs/betterspecs#173]
Continuation of #167 

Now that we have i18n translation ('translation' branch) we need to create YAML files for each language and move the translated texts to them. The translation keys must meet the ones used in the 'en' YAML.

Languages pending:
- [ ] Russian
- [ ] Taiwanese mandarin
- [ ] Chinese simplified
- [ ] Korean
- [ ] Japanese
- [ ] Brazilian portuguese
- [ ] Spanish
- [x] French

Guidelines:
- Use single quotes on HTML attributes
- Double quotes are used when the line needs to be broken

**Comment by akz92** [comment]
@benoittgt I know your task was to adapt the translated pages to the new layout, but since we only have one HTML file now can you help me with this?

**Comment by benoittgt** [comment]
Yep will be available tomorrow @akz92

**Comment by benoittgt** [comment]
Ok the french : https://github.com/lelylan/betterspecs/commit/68cc4e3d1ef8b37e85fe402e4ec5088d28e64549
