### ISSUE TITLE
Invalid SSL certificate for https://www.betterspecs.org

### ISSUE THREAD

**Issue by iainbeeston** [betterspecs/betterspecs#201]
If I view betterspecs.org over HTTPS I see a browser security error:

<img width="836" alt="Screenshot 2019-06-18 at 17 17 21" src="https://user-images.githubusercontent.com/111963/59701217-fded2f80-91ec-11e9-92b6-d8e9eca2fea7.png">

It seems that the SSL certificate for betterspecs.org is actually for *.herokuapp.com.

If you're using heroku to host the site and it uses paid dynos, heroku can provide you with an SSL certificate automatically. If you're using free dynos I believe you can set it up manually (for free) using [let's encrypt](https://letsencrypt.org/) and following the documentation for [heroku ssl](https://devcenter.heroku.com/articles/ssl#manually-uploading-certificates-and-intermediaries), or by using cloudflare as your DNS provider.

**Comment by benoittgt** [comment]
Thanks. Sadly I don't have access to that part of the application. :/

**Comment by akz92** [comment]
I'm unable to fix this for now as we use a free dyno on Heroku to host the website and it doesn't support SSL, but we're moving away from that and the new website already has SSL: [https://alpha.betterspecs.org](https://alpha.betterspecs.org)
