### ISSUE TITLE
Call for maintainer

### ISSUE THREAD

**Issue by andreareginato** [betterspecs/betterspecs#206]
Hi everyone, 

I'm opening this issue to look for a new maintainer who wants to take charge of the project betterspecs.org.

This means to take responsibility of the project in renewing the content and to take charge of the domain / hosting costs (which could be around 10€ per year).

I'll take 1 month from today.
If none will take responsibility of the project I'll set it as closed.

Thanks to everyone.
I look forward to hear from you in this issue.

**Comment by akz92** [comment]
Hey @andreareginato, I'll gladly take responsibility for it. Betterspecs has helped me immensely in the past and I'd love to help keep it alive for newcomers.

**Comment by andreareginato** [comment]
Hola @akz92.

Thanks a lot for sharing your interest, I very much appreciate.
Keep yourself into the next phase of the project.

I will take some more time for other people to share their interest too and then close the call for maintainer in order to try the creation of a small team (if possible) to make the transition lighter.

**Comment by bert-mccutchen** [comment]
Hey guys, the site seems to be down. Is there anything I can do to help?

**Comment by antgonzales** [comment]
@andreareginato site is down

**Comment by andreareginato** [comment]
@akz92  @bert-mccutchen sorry for the delay.

I would love to start the passage of the maintenance of the project betterspecs.

This will mean the following things
- @akz92 will be in charge of the porting of the site to the new platform (of its choice). @bert-mccutchen you will be collaborating in the new definition of the project.
- The whole responsibility is now assigned to the two of you (on decision, code, access, collaborators and whatever will be)
- The only think I would love to keep is my name in the fact that I was the person starting the project.

This said, I think we can get practical with the following tasks.
- you can create a new repository git where to port all the content (i propose to keep only english as now the translations services works way better than 5 years ago)
- I will pass the ownership of the domain betterspecs.org to @akz92

I think this should be enough to start. 
For anything else let me know.

Best

**Comment by akz92** [comment]
hey @andreareginato that sounds good! I've created an organization called `betterspecs` where we could keep the project and I've invited you and @bert-mccutchen. 

IMO it would be ideal if you could move the ownership of this repo to that org as it would allow us to keep all that's been registered here throughout these years (issues, stars, forks...).

> The only think I would love to keep is my name in the fact that I was the person starting the project.

That's more than fair, and if you accept to be a part of the org you can still help us if/when you feel like it :)

Please let me know if you need any info from me.

**Comment by endverbraucher** [comment]
@akz92 @bert-mccutchen thanks for taking over. I think I and my employer railslove would also support this project if there is anything we can help with (hosting for example)!

**Comment by andreareginato** [comment]
@akz92 feels perfect what you propose.

You are admin in the repo. I guess you can move freely on it and decide who can join and coordinate the new group. I hope @endverbraucher and partner can be part of this.

> ... I've created an organization called betterspecs where we could keep the project and I've invited you and @bert-mccutchen...
I did not see it in the notifications.
Am I missing something?

> ... if you accept to be a part of the org you can still help us if/when you feel like it ...
Please, I would love the next life of this project (I will also share some ideas I had in the past)

looking forward for this new phase to start.

**Comment by akz92** [comment]
@andreareginato I believe you can accept the invitation by going to [https://github.com/betterspecs](https://github.com/betterspecs). Bert has accepted it already.

I just transferred this repo to the new org, as soon as you pass me the ownership of the domain I'll but it back up. It would be awesome if you could transfer me the Heroku app as well if that's fine, my email there is aride.moulin@gmail.com.

> I hope @endverbraucher and partner can be part of this.
Absolutely! The more help we can get the better.

**Comment by andreareginato** [comment]
@akz92 
- Thanks for the guidance (I accepted the invitation)
- Transferred the Heroku app
- The domain ownership change is pending for approval 

If you need more, let me know ;)

**Comment by akz92** [comment]
Thanks @andreareginato, I've accepted the transfers and I believe that's all I'll need. :+1:

Our website `betterspecs.org` is back online now 🎉
