### ISSUE TITLE
Help needed to launch the new version of Betterspecs

### ISSUE THREAD

**Issue by akz92** [betterspecs/betterspecs#214]
After a few years of inactivity Betterspecs is getting back on its feet, we're working hard to have the new version of the website launched soon. This new version is really exciting as we move away from an outdated environment and into a fresh and up-to-date continuous deployment environment.

Betterspecs 2.0 relies on Jekyll which removes the need of having a dedicated server. The initial plan was to use Github Pages so we'd have hassle-free deployment and less overhead as we wouldn't need to maintain any other accounts or servers but it didn't work out the way we planned.   Github Pages doesn't support Jekyll plugins (at least not custom ones) and we rely on them to have multi-language support. I chose Netlify as its replacement as it's free and integrates nicely with Github so we don't need to do anything other than merge PRs to update the live website.

I've made great progress on the last few days to get this new version out and the only missing part now is adding the (existing) translations. Here's a list of all languages we support and the ones we've already added:

- [x] English
- [ ] Russian
- [ ] Taiwanese mandarin
- [ ] Chinese simplified
- [ ] Korean
- [ ] Japanese
- [x] Brazilian Portuguese
- [ ] Spanish
- [x] French

This is basically a manual process but I believe it'd be best if someone who speaks the language did each so they'll know better how to do it. There's also missing translations that need to be added, so doing all of this at once sounds better to me.

If you can help with any of the languages missing please let us know 🙏 

If you're curious about the new version we've got a alpha version live: [https://alpha.betterspecs.org](https://alpha.betterspecs.org)

**Comment by akz92** [comment]
@bert-mccutchen @endverbraucher tagging you here in case you (or someone you know) can help with any of the pending languages :)

**Comment by bert-mccutchen** [comment]
Hey @akz92, sorry for the late reply. I don't seem to be getting notifications about anything that is happening here and I run a pretty busy schedule.

Unfortunately I cannot help here in the translation department. However, I do believe with this new release, for legal reasons, we should probably drop the Lelylan branding. I say this because Lelylan has removed themselves from the project, so now Betterspecs is a separate entity using their branding. That being said, I think we should still keep the nod to Lelylan in the introduction for their efforts.

I have some contacts that can probably help with a new logo if you'd like.

**Comment by akz92** [comment]
That's a valid point! I'd appreciate your help with the logo as that's completely outside of my area of expertise :)

**Comment by andreareginato** [comment]
I share a thought about the translations.
TLTR: we don't really need translation.

What do I mean?

I mean that nowadays we have translation tools that works great and that at the same time to keep the translations always in sync is much harder than it looks. I loved the involvement of the community who contributed at the project when it started, but I think now is time to make it more agile.

My 2 cents.

@akz92 you are doing a great job, my deep compliments

**Comment by akz92** [comment]
@andreareginato that's a very good point, and it would also mean way less overhead in maintaining the project up-to-date. As a bonus it would also allow us to use Github pages since we wouldn't need any plugins anymore.

I'll try to have an English-only version deployed and that from their we might get feedback in case people miss the translations.

**Comment by andreareginato** [comment]
I look forward to see the new version online.
Keep on with the great job

**Comment by andreareginato** [comment]
@akz92 how is the migration going?

**Comment by akz92** [comment]
@andreareginato I finally got some time to finish the new version today. You can see the final result [here](https://blissful-lalande-8166e8.netlify.app/). Now I'm configuring our domain to point to the new version so it might be offline for a while.

**Comment by akz92** [comment]
So, the new version seems to be working fine after all. @andreareginato thanks for your help here!
