### ISSUE TITLE
link to method documentation

### ISSUE THREAD

**Issue by afeld** [betterspecs/betterspecs#59]
E.g. if someone's never used `context` before, they will want to see other examples of how it's used.  I imagine in most cases this will link to the [RDoc](http://rubydoc.info/gems/rspec-core/file/README.md#shared_examples_and_contexts) and/or [Relish](https://www.relishapp.com/rspec/rspec-core/v/2-13/docs/example-groups/basic-structure-describe-it!#nested-example-groups-%28using-context%29) pages.

**Comment by onebree** [comment]
I agree. `context` is an abstract concept, as you can use it with vanilla RSpec DSL _and_ Capybara DSL. You may submit a PR if you'd like, along with a code block or two demonstrating what context does.

**Comment by akz92** [comment]
This's been around for a long time without activity, closing it for now.
