### ISSUE TITLE
Random specs

### ISSUE THREAD

**Issue by lucianosousa** [betterspecs/betterspecs#68]
In order that capture related spec, I suggest put a topic about random specs.
I saw a lot of projects not using (and disabling this option from rspec)

**Comment by onebree** [comment]
@lucianosousa  As you may have seen, your PR was closed. We can discuss this further if you'd like. 

In my opinion, I think it is best practice to enable random specs. Doing such shows all specs are independent. This is important for both Unit and Integrated testing.

You may create a _new_ PR explaining the option in RSpec 2 _and_ 3. Also include that in RSpec 3, you would place the random option in the `spec_helper.rb` and preferably not the `rails_helper.rb`

If this sounds unfamiliar to you, I will put this issue on hold until we update the site.
