### ISSUE TITLE
Redesign for better Multilanguage

### ISSUE THREAD

**Issue by muescha** [betterspecs/betterspecs#78]
this issue is for putting together all ideas and people who want to make a good redesign.

(see #20 )

**Comment by onebree** [comment]
I would like to update everyone by taking a look at this comment I made on another issue:  

@onebree said in https://github.com/andreareginato/betterspecs/issues/65#issuecomment-108653852
>When we change the format of the site, we can haven links to the country flag, which points the user to a translated version of the site. This is why Pages would be good, because it will be easier to format other languages (using ** for bold) and to render partials dependent on a parameter passed to the URL (like `[language]=de`)

Basically, I plan to overhaul the site and move it to Github Pages with Jekyll, where we can edit content with Markdown. This will make it much easier to read (as Github renders markdown), view changes, and organize views.

**Comment by akz92** [comment]
this seems to have been achieved overall now that we're not doing translations anymore. 🙂
